Release/111 (#1)
* only build necessary target (#43)

* Bump to 111.6.1+1.1.1d

* Update checkout actions reference

* Fixed apparent typo in the readme (#46)

* Work around upstream cargo issues

* Add handling for target riscv64gc-unknown-linux-gnu (#48)

* Disable asmjs for now

* Allow to specify custom path for Perl (#49)

* Allow to specify custom path for Perl

Env var OPENSSL_SRC_PERL can be set to specify
a path to the perl binary to use to call the openssl
perl scripts.

Resolves #45

* Fallback to PERL env var if OPENSSL_SRC_PERL is not set

* Add support for non-x86 archs on FreeBSD (#50)

Caused by:
  process didn't exit successfully: `.../rust-bootstrap/work-aarch64/rustc-1.40.0-src/build/x86_64-unknown-freebsd/stage1-tools/release/build/openssl-sys-4b2d35028bf73953/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn

--- stderr
thread 'main' panicked at 'don't know how to configure OpenSSL for aarch64-unknown-freebsd', .../rust-bootstrap/work-aarch64/rustc-1.40.0-src/vendor/openssl-src/src/lib.rs:178:18

* Update CI installation of Rust on macos~

* support for illumos systems (#52)

Resolves #51

* More comment out of asmjs

* Use gmake by default on all DragonFlyBSD, FreeBSD or Solaris targets (#53)

* Bump to 1.1.1e (#54)

* Add support for illumos triple (#56)

* Bump to 1.1.1f (#58)

* Release 111.8.1+1.1.1f

* Bump to 1.1.1g

* Do not overwrite AR and RANLIB env vars if set (#62)

* Add engine support for linux-gnu (#63)

* add engine support for linux-gnu

Signed-off-by: Xintao <hunterlxt@live.com>

* address comment

Signed-off-by: Xintao <hunterlxt@live.com>

* add blacklist os

Signed-off-by: Xintao <hunterlxt@live.com>

* add blacklist os

Signed-off-by: Xintao <hunterlxt@live.com>

* To check CI build info

Signed-off-by: Xintao <hunterlxt@live.com>

* add comments

Signed-off-by: Xintao <hunterlxt@live.com>

* Bump to 111.10.0+1.1.1g

* Fix build on macOS with latest cc crate (#67)

cc v1.0.58 broke the macOS build by including the "-arch" flag in the
default set of compiler flags. Strip it out, like we do for iOS targets.

Closes #66.

* Bump to 111.10.1+1.1.1g

* add optional features for less used algorithms (#68)

This commit disables by default a few of the weaker cryptographical algorithms into
a "weak-crypto" feature as well as some of the less used algorithms into
their own specific features.
These algorithms are not directly exposed through the rust-openssl crate.
The compilation of these can be re-enabled by selecting the desired features.
This should slightly reduce build time and library size.

Signed-off-by: Petre Eftime <petre.eftime@gmail.com>

* Bump to 111.10.2+1.1.1g

* Bump to 1.1.1h (#73)

* Add FreeBSD powerpc64le support (#75)

FreeBSD PowerPC64LE is a new target.

This is needed to cross-build cargo.

* Add upstream patch to allow building on aarch64-apple-darwin (#74)

* Use fs module convenience methods for MUSL patch

* Add upstream patch to allow building on aarch64-apple-darwin

Closes #72

* i586 support (#76)

* Bump to 111.12.0+1.1.1h

* Add aarch64-apple-darwin to CI (#77)

* OpenBSD support (#78)

* Update OpenSSL to 1.1.1i

* Update CI

* Remove now no-longer-necessary patches

* Support targets `armv7-unknown-linux-gnueabi/musleabi` (#80)

Support targets `armv7-unknown-linux-gnueabi` & `armv7-unknown-linux-musleabi`

* Make it compile for wasm32-wasi (#81)

* Catch more failures on Windows in CI (#84)

* Catch more failures on Windows in CI

* Link missing library for OpenSSL on MSVC

Looks like some functions may pull in user32 functions, so that library
needs to be linked.

* Try to fix msvc +crt-static builds

* Try to see all failures

* More output

* Fix setting crt-static

* More CI tweaks

* Add the bin dir to cargo's search path on MSVC

That's where it contains the actual dlls needed at runtime

* Moved "no-shared" so that also windows statically link to the libraries (#83)

* Moved "no-shared" so that windows statically link to the libraries

* try reapplying changes

* removed shared as it's always false.

Co-authored-by: molleafauss <lmollea@yahoo.it>

* Bump to OpenSSL 1.1.1j (#85)

* add nasm support for msvc (#87)

* add nasm support for windows-msvc

This will automatically detect whether nasm.exe is installed and
try to enable the assembly language routines. These can also be
disabled by set the `OPENSSL_RUST_NO_NASM` environment variable to
a non-zero value.

* don't use '>> $GITHUB_ENV' to overwrite PATH

* remove the windows check in CI

* give user more control on the env var

* add env var in CI, less acceptable values for env var

* fix path format for using bash on windows

* 'OPENSSL_RUST_USE_NASM' env var only accept 0 or 1

* Bump to 1.1.1k

* Add FreeBSD powerpc support (#90)

This is needed to support cargo cross-build for 32-bit powerpc on FreeBSD.

* Upgrade to GitHub-native Dependabot (#92)

Co-authored-by: dependabot-preview[bot] <27856297+dependabot-preview[bot]@users.noreply.github.com>

* Support targets `armv5te-unknown-linux-gnueabi/musleabi` (#94)

* Support targets `popwerpc64(le)-unknown-linux-musl` (#95)

* Support targets `mips64(el)-unknown-linux-muslabi64` (#96)

* Support target `s390x-unknown-linux-musl` (#97)

* Bump to openssl 1.1.1l (#100)

* Bump to 1.1.1m

* test on 1.1.1 branch

* Fix aarch64-apple-darwin CI (#116)

(cherry picked from commit 466ffd201be07d0137e373de3aac2349b9063e93)

* Bump to 1.1.1n (#123)

* Update "old" windows image on CI (#126)

* Bump to 1.1.1o (#136)

* Bump to 1.1.1o

* Disable arm-linux-androideabi test

* Backport wycheproof exclude to 1.1.1 branch (#139)

* Backport wycheproof exclude to 1.1.1 branch

* Backport exclude CI checks

* Backport exclude CI checks

* Configure `--openssldir` to its default location (#141) (#142)

As pointed out in #140 otherwise certificates and configure is by
default looked up in the directory of the build machine itself which is
often a writable path. Instead switch the configuration option back to
the default recommended in openssl's `INSTALL.md`

Closes #140

* Bump to 111.20.0+1.1.1o (#143)

* Bump to 1.1.1p (#145)

* Bump to 1.1.1q (#147)

Co-authored-by: Jay <BusyJay@users.noreply.github.com>
Co-authored-by: Alex Crichton <alex@alexcrichton.com>
Co-authored-by: Alex Gaynor <alex.gaynor@gmail.com>
Co-authored-by: msizanoen1 <55322658+msizanoen1@users.noreply.github.com>
Co-authored-by: Franck Royer <royer.franck@gmail.com>
Co-authored-by: Tobias Kortkamp <t6@users.noreply.github.com>
Co-authored-by: Joshua M. Clulow <josh@sysmgr.org>
Co-authored-by: MikaelUrankar <49529234+MikaelUrankar@users.noreply.github.com>
Co-authored-by: Steven Fackler <sfackler@gmail.com>
Co-authored-by: Patrick Mooney <pmooney@pfmooney.com>
Co-authored-by: Steven Fackler <sfackler@palantir.com>
Co-authored-by: James McMurray <jamesmcm03@gmail.com>
Co-authored-by: Xintao <hunterlxt@live.com>
Co-authored-by: Nikhil Benesch <nikhil.benesch@gmail.com>
Co-authored-by: petreeftime <petre.eftime@gmail.com>
Co-authored-by: Brandon Bergren <git@bdragon.rtk0.net>
Co-authored-by: Jake Goulding <shepmaster@mac.com>
Co-authored-by: Will <will@mon.im>
Co-authored-by: Jake Goulding <jake.goulding@gmail.com>
Co-authored-by: kiron1 <kiron1@gmail.com>
Co-authored-by: IceCodeNew <32576256+IceCodeNew@users.noreply.github.com>
Co-authored-by: Pierre Krieger <pierre.krieger1708@gmail.com>
Co-authored-by: Alex Malgaroli <alex.malgaroli@gmail.com>
Co-authored-by: molleafauss <lmollea@yahoo.it>
Co-authored-by: Kane <KaneGreen@users.noreply.github.com>
Co-authored-by: Brandon Bergren <bdragon@FreeBSD.org>
Co-authored-by: dependabot-preview[bot] <27856297+dependabot-preview[bot]@users.noreply.github.com>
Co-authored-by: messense <messense@icloud.com>
Co-authored-by: Alexis Mousset <contact@amousset.me>
Co-authored-by: Eric Huss <eric@huss.org>
Co-authored-by: Alexis Mousset <alexis.mousset@rudder.io>